// radioCatalog.js — station and track definitions for the in-car radio.
//
// These are not recordings: every field here feeds a real synthesiser in audio/musicgen.js,
// so the drum grids, chord movements and bass patterns are the actual music.

// 16-step helpers keep the drum grids readable.
const K = (...steps) => { const a = new Array(16).fill(0); for (const s of steps) a[s] = 1; return a; };
const KV = (pairs) => { const a = new Array(16).fill(0); for (const [i, v] of pairs) a[i] = v; return a; };
const HAT = (v1, v2) => Array.from({ length: 16 }, (_, i) => (i % 2 === 0 ? v1 : v2));

export const STATIONS = Object.freeze([
  {
    id: 'neon-drive', name: 'NEON DRIVE 101.7', tagline: 'Synthwave after dark', genre: 'synthwave',
    color: 0xff2d95, djName: 'Halo Vex',
    tracks: [
      { title: 'Chrome Coastline', artist: 'Velvet Static', bpm: 112, bars: 8, swing: 0,
        key: 9, scale: 'minor', progression: [0, 5, 3, 4],
        drums: { kick: K(0, 4, 8, 12), snare: K(4, 12), hat: HAT(0.7, 0.35), clap: K(4, 12) },
        bass: { wave: 'saw', octave: 2, cutoff: 900, glide: 0.04,
          pattern: [0, null, 0, 0, null, 0, null, 0, 3, null, 3, null, 4, null, 4, 4] },
        lead: { wave: 'saw', octave: 5, cutoff: 2600, delay: 0.28, on: true,
          pattern: [7, null, 5, 4, null, 3, null, 4, 5, null, null, 7, null, 9, 7, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1400, on: true, attack: 1.2, release: 2.0 },
        arp: { wave: 'square', octave: 5, rate: 4, on: true },
        energy: 0.78 },
      { title: 'Midnight Interceptor', artist: 'Kobra Lux', bpm: 124, bars: 8, swing: 0,
        key: 2, scale: 'phrygian', progression: [0, 1, 0, 6],
        drums: { kick: K(0, 3, 6, 8, 11, 14), snare: K(4, 12), hat: HAT(0.55, 0.3), open: K(7, 15) },
        bass: { wave: 'square', octave: 2, cutoff: 1100, glide: 0.02,
          pattern: [0, 0, null, 0, 0, null, 0, 1, 1, null, 1, null, 6, null, 6, 6] },
        lead: { wave: 'saw', octave: 5, cutoff: 3200, delay: 0.22, on: true,
          pattern: [0, 3, 5, 7, 5, 3, null, 0, 7, null, 5, 3, 2, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1100, on: true, attack: 0.9, release: 1.6 },
        energy: 0.88 },
      { title: 'Pastel Horizon', artist: 'Cassette Sunrise', bpm: 98, bars: 8, swing: 0.05,
        key: 5, scale: 'major', progression: [0, 3, 4, 3],
        drums: { kick: K(0, 8), snare: K(4, 12), hat: HAT(0.42, 0.22), ride: K(0, 4, 8, 12) },
        bass: { wave: 'sine', octave: 2, cutoff: 700,
          pattern: [0, null, null, 0, null, 4, null, null, 3, null, null, 3, null, 4, null, null] },
        lead: { wave: 'triangle', octave: 5, cutoff: 2100, delay: 0.4, on: true,
          pattern: [4, null, 5, null, 7, null, null, 5, 4, null, 2, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 4, cutoff: 1600, on: true, attack: 2.0, release: 2.6 },
        energy: 0.5 },
      { title: 'Laser Boulevard', artist: 'Velvet Static', bpm: 132, bars: 8, swing: 0,
        key: 0, scale: 'minor', progression: [0, 5, 6, 4],
        drums: { kick: K(0, 4, 8, 12), snare: K(4, 12), hat: HAT(0.8, 0.4), open: K(14), clap: K(4, 12) },
        bass: { wave: 'saw', octave: 2, cutoff: 1400, glide: 0.03,
          pattern: [0, 0, 0, null, 0, 0, null, 0, 5, 5, null, 5, 6, 6, 4, 4] },
        lead: { wave: 'square', octave: 6, cutoff: 3600, delay: 0.18, on: true,
          pattern: [0, 2, 3, 5, 7, 5, 3, 2, 0, 2, 3, 7, 5, 3, 2, 0] },
        pad: { wave: 'saw', octave: 3, cutoff: 1300, on: true, attack: 0.7, release: 1.4 },
        arp: { wave: 'saw', octave: 6, rate: 8, on: true },
        energy: 0.95 },
    ],
    idents: ['Neon Drive — the city never sleeps and neither do we.',
      'You are locked in to one-oh-one point seven.',
      'Keep both hands on the wheel. Or don\'t. I\'m a radio, not your mother.',
      'Sunset is in forty minutes. Be somewhere worth watching it from.'],
    ads: [{ brand: 'Atomic Cola', line: 'Tastes like a decision you will regret.' },
      { brand: 'Veloce Motors', line: 'If you have to ask the price, we have already sold it.' }],
  },
  {
    id: 'radio-calor', name: 'RADIO CALOR 92.3', tagline: 'El ritmo de Leonida', genre: 'latin',
    color: 0xff7a29, djName: 'Chava Ruiz',
    tracks: [
      { title: 'Fuego Lento', artist: 'Los Marlines', bpm: 96, bars: 8, swing: 0.14,
        key: 4, scale: 'minor', progression: [0, 5, 3, 4],
        drums: { kick: K(0, 3, 6, 10), snare: K(4, 12), hat: HAT(0.6, 0.42), clap: K(6, 14), tom: K(11) },
        bass: { wave: 'triangle', octave: 2, cutoff: 800,
          pattern: [0, null, 0, null, 4, null, 3, null, 0, null, 0, 2, 4, null, 4, null] },
        lead: { wave: 'triangle', octave: 5, cutoff: 2200, delay: 0.2, on: true,
          pattern: [0, 2, 3, null, 2, 0, null, 3, 5, 3, 2, null, 0, null, null, null] },
        pad: { wave: 'triangle', octave: 4, cutoff: 1500, on: true, attack: 0.8, release: 1.2 },
        energy: 0.72 },
      { title: 'Bajo la Luna', artist: 'Yolanda Cruz', bpm: 88, bars: 8, swing: 0.18,
        key: 7, scale: 'dorian', progression: [0, 3, 4, 0],
        drums: { kick: K(0, 6, 8, 14), snare: K(4, 12), hat: HAT(0.5, 0.3), ride: K(2, 6, 10, 14) },
        bass: { wave: 'sine', octave: 2, cutoff: 640,
          pattern: [0, null, null, 3, null, 0, null, null, 4, null, 4, null, 3, null, null, null] },
        lead: { wave: 'sine', octave: 5, cutoff: 1800, delay: 0.32, on: true,
          pattern: [5, 4, null, 3, null, 2, 3, null, 4, null, null, 0, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1200, on: true, attack: 1.5, release: 2.2 },
        energy: 0.44 },
      { title: 'Malecón', artist: 'Trio Habanero', bpm: 104, bars: 8, swing: 0.16,
        key: 2, scale: 'mixolydian', progression: [0, 4, 5, 4],
        drums: { kick: K(0, 3, 8, 11), snare: K(4, 12), hat: HAT(0.66, 0.4), tom: K(7, 15), clap: K(12) },
        bass: { wave: 'triangle', octave: 2, cutoff: 900,
          pattern: [0, 0, null, 4, null, 4, null, 5, 5, null, 4, null, 0, null, 0, null] },
        lead: { wave: 'square', octave: 5, cutoff: 2400, delay: 0.16, on: true,
          pattern: [4, 5, 7, null, 5, 4, 2, null, 0, 2, 4, null, 2, null, null, null] },
        pad: { wave: 'triangle', octave: 4, cutoff: 1700, on: true, attack: 0.6, release: 1.0 },
        energy: 0.82 },
      { title: 'Corazón de Asfalto', artist: 'Los Marlines', bpm: 112, bars: 8, swing: 0.12,
        key: 9, scale: 'harmonicMinor', progression: [0, 5, 4, 0],
        drums: { kick: K(0, 4, 7, 10, 14), snare: K(4, 12), hat: HAT(0.7, 0.45), clap: K(4, 12) },
        bass: { wave: 'saw', octave: 2, cutoff: 1000,
          pattern: [0, null, 0, 2, 4, null, 4, null, 5, null, 4, null, 0, 0, null, 7] },
        lead: { wave: 'saw', octave: 5, cutoff: 2800, delay: 0.2, on: true,
          pattern: [7, null, 5, 4, 5, null, 4, 2, 0, null, 2, 4, null, null, 0, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1300, on: true, attack: 0.9, release: 1.5 },
        energy: 0.86 },
    ],
    idents: ['Radio Calor, noventa y dos punto tres — the hottest thing on this coast.',
      'If your air conditioning is broken, turn us up instead.',
      'Dedications, requests, apologies — call the station.'],
    ads: [{ brand: 'Mango Bravo', line: 'Fruit juice with an attitude problem.' },
      { brand: 'Casa Iguana', line: 'Family dining. Your family, our iguana.' }],
  },
  {
    id: 'kult-fm', name: 'KULT FM 88.5', tagline: 'Hip-hop from the flats', genre: 'hiphop',
    color: 0xffc93c, djName: 'DJ Sable',
    tracks: [
      { title: 'Flats Anthem', artist: 'Mook Delray', bpm: 88, bars: 8, swing: 0.18,
        key: 3, scale: 'minor', progression: [0, 0, 5, 3],
        drums: { kick: KV([[0, 1], [3, 0.7], [6, 0.5], [10, 1], [11, 0.6]]), snare: K(4, 12),
          hat: HAT(0.62, 0.34), open: K(14) },
        bass: { wave: 'sine', octave: 1, cutoff: 480, glide: 0.06,
          pattern: [0, null, null, 0, null, null, 3, null, 5, null, null, 5, null, 3, null, null] },
        lead: { wave: 'triangle', octave: 4, cutoff: 1400, delay: 0.34, on: true,
          pattern: [0, null, 3, null, 5, null, 3, null, 2, null, 0, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 900, on: true, attack: 1.4, release: 2.2 },
        energy: 0.7 },
      { title: 'Glass House', artist: 'Nite Marlo', bpm: 84, bars: 8, swing: 0.2,
        key: 8, scale: 'minor', progression: [0, 3, 5, 4],
        drums: { kick: KV([[0, 1], [7, 0.8], [10, 1]]), snare: K(4, 12), hat: HAT(0.5, 0.26), clap: K(12) },
        bass: { wave: 'sine', octave: 1, cutoff: 420,
          pattern: [0, null, null, null, 3, null, null, null, 5, null, null, null, 4, null, null, null] },
        lead: { wave: 'sine', octave: 5, cutoff: 1700, delay: 0.42, on: true,
          pattern: [7, null, null, 5, null, 4, null, null, 3, null, null, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 820, on: true, attack: 1.9, release: 2.6 },
        energy: 0.48 },
      { title: 'Trunk Rattle', artist: 'Big Sarge', bpm: 76, bars: 8, swing: 0.14,
        key: 1, scale: 'phrygian', progression: [0, 1, 0, 6],
        drums: { kick: KV([[0, 1], [2, 0.6], [6, 0.9], [8, 1], [12, 0.8], [14, 0.6]]), snare: K(4, 12),
          hat: HAT(0.72, 0.4), open: K(11) },
        bass: { wave: 'square', octave: 1, cutoff: 560, glide: 0.08,
          pattern: [0, 0, null, 0, null, 1, null, 1, 0, null, 0, null, 6, null, 6, null] },
        lead: { wave: 'square', octave: 4, cutoff: 1600, delay: 0.26, on: true,
          pattern: [0, null, 1, null, 0, null, null, 6, null, null, 5, null, 3, null, null, null] },
        pad: { wave: 'saw', octave: 2, cutoff: 700, on: true, attack: 1.1, release: 1.8 },
        energy: 0.9 },
      { title: 'Causeway Cruise', artist: 'DJ Sable', bpm: 92, bars: 8, swing: 0.16,
        key: 6, scale: 'dorian', progression: [0, 3, 0, 4],
        drums: { kick: KV([[0, 1], [3, 0.6], [8, 1], [11, 0.7]]), snare: K(4, 12), hat: HAT(0.58, 0.3), ride: K(2, 10) },
        bass: { wave: 'triangle', octave: 2, cutoff: 640,
          pattern: [0, null, 0, null, 3, null, null, 3, 0, null, 0, null, 4, null, 4, null] },
        lead: { wave: 'triangle', octave: 5, cutoff: 1900, delay: 0.3, on: true,
          pattern: [3, 5, null, 7, null, 5, 3, null, 0, null, 3, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1000, on: true, attack: 1.3, release: 2.0 },
        energy: 0.66 },
    ],
    idents: ['KULT eighty-eight five. You know what it is.',
      'Shout out to everybody stuck on the causeway right now.',
      'We play what the block plays.'],
    ads: [{ brand: 'Domino Wheels', line: 'Rims so clean your car forgets where it came from.' },
      { brand: 'Sabre Energy', line: 'Sleep is a habit. Habits can be broken.' }],
  },
  {
    id: 'wave-98', name: 'WAVE 98', tagline: 'Soul and sunshine', genre: 'soul',
    color: 0x4dff9e, djName: 'Marlene Pryce',
    tracks: [
      { title: 'Golden Hour', artist: 'The Pelican Set', bpm: 102, bars: 8, swing: 0.15,
        key: 5, scale: 'major', progression: [0, 5, 1, 4],
        drums: { kick: K(0, 8, 10), snare: K(4, 12), hat: HAT(0.5, 0.32), ride: K(0, 2, 4, 6, 8, 10, 12, 14) },
        bass: { wave: 'triangle', octave: 2, cutoff: 720,
          pattern: [0, null, 2, 4, null, 5, null, 4, 1, null, 3, null, 4, null, 2, null] },
        lead: { wave: 'sine', octave: 5, cutoff: 2000, delay: 0.24, on: true,
          pattern: [4, null, 5, 7, null, 5, 4, null, 2, null, 4, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 4, cutoff: 1500, on: true, attack: 1.0, release: 1.8 },
        energy: 0.62 },
      { title: 'Letter to the Bay', artist: 'Odell Grant', bpm: 78, bars: 8, swing: 0.2,
        key: 10, scale: 'major', progression: [0, 3, 4, 0],
        drums: { kick: K(0, 8), snare: K(4, 12), hat: HAT(0.38, 0.2) },
        bass: { wave: 'sine', octave: 2, cutoff: 560,
          pattern: [0, null, null, null, 3, null, null, null, 4, null, null, 2, 0, null, null, null] },
        lead: { wave: 'sine', octave: 4, cutoff: 1600, delay: 0.36, on: true,
          pattern: [2, 4, null, 5, null, 4, 2, null, 0, null, null, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1150, on: true, attack: 2.2, release: 3.0 },
        energy: 0.36 },
      { title: 'Boardwalk Strut', artist: 'The Pelican Set', bpm: 116, bars: 8, swing: 0.13,
        key: 3, scale: 'mixolydian', progression: [0, 4, 5, 4],
        drums: { kick: K(0, 6, 8, 14), snare: K(4, 12), hat: HAT(0.62, 0.36), clap: K(4, 12), tom: K(15) },
        bass: { wave: 'triangle', octave: 2, cutoff: 820,
          pattern: [0, 0, null, 4, null, 4, 5, null, 4, null, 2, null, 0, null, 0, 0] },
        lead: { wave: 'square', octave: 5, cutoff: 2300, delay: 0.2, on: true,
          pattern: [0, 2, 4, 5, 4, 2, 0, null, 4, 5, 7, null, 5, 4, 2, null] },
        pad: { wave: 'saw', octave: 4, cutoff: 1600, on: true, attack: 0.7, release: 1.2 },
        energy: 0.8 },
      { title: 'Salt and Static', artist: 'Marlene Pryce', bpm: 94, bars: 8, swing: 0.17,
        key: 8, scale: 'minor', progression: [0, 6, 3, 4],
        drums: { kick: K(0, 7, 8), snare: K(4, 12), hat: HAT(0.46, 0.26), ride: K(2, 6, 10, 14) },
        bass: { wave: 'sine', octave: 2, cutoff: 640,
          pattern: [0, null, 0, null, 6, null, null, 6, 3, null, 3, null, 4, null, null, null] },
        lead: { wave: 'triangle', octave: 5, cutoff: 1900, delay: 0.3, on: true,
          pattern: [0, 3, null, 4, null, 3, 0, null, 6, null, 4, null, 3, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1250, on: true, attack: 1.6, release: 2.4 },
        energy: 0.5 },
    ],
    idents: ['Wave ninety-eight. Warm all the way through.',
      'A little something for the drive home.',
      'That was for whoever needed it.'],
    ads: [{ brand: 'Orchid Linens', line: 'Sheets so soft you may never leave.' },
      { brand: 'Pearl Diner', line: 'Open since before you were a problem.' }],
  },
  {
    id: 'pulse-fm', name: 'PULSE FM 105.9', tagline: 'House, all night', genre: 'house',
    color: 0x22e3ff, djName: 'Ines Quay',
    tracks: [
      { title: 'Four On The Causeway', artist: 'Ines Quay', bpm: 126, bars: 8, swing: 0,
        key: 0, scale: 'minor', progression: [0, 0, 5, 5],
        drums: { kick: K(0, 4, 8, 12), snare: K(4, 12), hat: HAT(0.3, 0.75), open: K(2, 6, 10, 14), clap: K(4, 12) },
        bass: { wave: 'saw', octave: 2, cutoff: 1000,
          pattern: [null, 0, 0, null, null, 0, 0, null, null, 5, 5, null, null, 5, 5, null] },
        lead: { wave: 'saw', octave: 5, cutoff: 2600, delay: 0.24, on: true,
          pattern: [0, null, 3, null, 5, null, 3, null, 7, null, 5, null, 3, null, null, null] },
        pad: { wave: 'saw', octave: 4, cutoff: 1700, on: true, attack: 1.2, release: 2.0 },
        arp: { wave: 'square', octave: 6, rate: 8, on: true },
        energy: 0.88 },
      { title: 'Deep End', artist: 'Cobalt Room', bpm: 120, bars: 8, swing: 0,
        key: 7, scale: 'dorian', progression: [0, 3, 0, 5],
        drums: { kick: K(0, 4, 8, 12), snare: K(12), hat: HAT(0.26, 0.6), open: K(6, 14) },
        bass: { wave: 'sine', octave: 2, cutoff: 760,
          pattern: [0, null, null, 0, null, null, 3, null, 0, null, null, 0, null, 5, null, null] },
        lead: { wave: 'triangle', octave: 5, cutoff: 2000, delay: 0.38, on: true,
          pattern: [3, null, null, 5, null, null, 7, null, 5, null, null, 3, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1300, on: true, attack: 2.0, release: 2.8 },
        energy: 0.6 },
      { title: 'Strobe Palm', artist: 'Ines Quay', bpm: 130, bars: 8, swing: 0,
        key: 4, scale: 'minor', progression: [0, 6, 5, 3],
        drums: { kick: K(0, 4, 8, 12), snare: K(4, 12), hat: HAT(0.32, 0.8), open: K(2, 6, 10, 14), clap: K(4, 12), ride: K(0, 8) },
        bass: { wave: 'square', octave: 2, cutoff: 1300, glide: 0.02,
          pattern: [0, 0, null, 0, 6, null, 6, null, 5, 5, null, 5, 3, null, 3, null] },
        lead: { wave: 'saw', octave: 5, cutoff: 3400, delay: 0.18, on: true,
          pattern: [0, 3, 5, 7, 5, 3, 0, 3, 5, 7, 10, 7, 5, 3, 0, null] },
        pad: { wave: 'saw', octave: 4, cutoff: 1800, on: true, attack: 0.8, release: 1.4 },
        arp: { wave: 'saw', octave: 6, rate: 16, on: true },
        energy: 1.0 },
      { title: 'Blue Room', artist: 'Cobalt Room', bpm: 118, bars: 8, swing: 0,
        key: 11, scale: 'minor', progression: [0, 5, 3, 4],
        drums: { kick: K(0, 4, 8, 12), snare: K(4, 12), hat: HAT(0.28, 0.62), clap: K(12) },
        bass: { wave: 'saw', octave: 2, cutoff: 880,
          pattern: [0, null, 0, null, 5, null, 5, null, 3, null, 3, null, 4, null, 4, null] },
        lead: { wave: 'sine', octave: 5, cutoff: 2200, delay: 0.34, on: true,
          pattern: [7, null, null, null, 5, null, null, null, 4, null, null, null, 3, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1500, on: true, attack: 1.7, release: 2.4 },
        energy: 0.72 },
    ],
    idents: ['Pulse one-oh-five nine. Keep moving.',
      'This is the part of the night where decisions get interesting.',
      'No talking over the drop. House rules.'],
    ads: [{ brand: 'Vortex Club', line: 'Doors at eleven. Regret at six.' },
      { brand: 'Glimmer Water', line: 'It is water. It costs more.' }],
  },
  {
    id: 'iron-lung', name: 'IRON LUNG 66.6', tagline: 'Loud and unrepentant', genre: 'metal',
    color: 0xff3b30, djName: 'Gristle',
    tracks: [
      { title: 'Foundry Teeth', artist: 'Rust Sabbath', bpm: 152, bars: 8, swing: 0,
        key: 4, scale: 'phrygian', progression: [0, 1, 0, 5],
        drums: { kick: KV([[0, 1], [1, 0.9], [2, 1], [3, 0.9], [8, 1], [9, 0.9], [10, 1], [11, 0.9]]),
          snare: K(4, 12), hat: HAT(0.8, 0.55), ride: K(0, 2, 4, 6, 8, 10, 12, 14) },
        bass: { wave: 'saw', octave: 1, cutoff: 1200,
          pattern: [0, 0, 0, 0, 1, 1, null, 0, 0, 0, null, 0, 5, 5, null, 5] },
        lead: { wave: 'saw', octave: 4, cutoff: 3000, delay: 0.12, on: true,
          pattern: [0, null, 1, null, 0, null, 5, null, 3, null, 1, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 2, cutoff: 800, on: true, attack: 0.4, release: 0.8 },
        energy: 1.0 },
      { title: 'Salt Corroded', artist: 'Hollow Anchor', bpm: 138, bars: 8, swing: 0,
        key: 9, scale: 'minor', progression: [0, 6, 5, 0],
        drums: { kick: KV([[0, 1], [3, 0.8], [6, 1], [8, 1], [11, 0.8], [14, 1]]), snare: K(4, 12),
          hat: HAT(0.7, 0.45), open: K(15) },
        bass: { wave: 'square', octave: 1, cutoff: 980,
          pattern: [0, null, 0, 0, null, 6, null, 6, 5, null, 5, null, 0, 0, null, 0] },
        lead: { wave: 'saw', octave: 4, cutoff: 2700, delay: 0.16, on: true,
          pattern: [0, 3, 5, null, 3, 0, null, 6, 5, null, 3, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 2, cutoff: 700, on: true, attack: 0.5, release: 1.0 },
        energy: 0.92 },
      { title: 'Hurricane Season', artist: 'Rust Sabbath', bpm: 168, bars: 8, swing: 0,
        key: 2, scale: 'harmonicMinor', progression: [0, 5, 1, 0],
        drums: { kick: KV([[0, 1], [1, 1], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1], [8, 1], [9, 1], [10, 1], [11, 1], [12, 1], [13, 1], [14, 1], [15, 1]]),
          snare: K(4, 12), hat: HAT(0.85, 0.6) },
        bass: { wave: 'saw', octave: 1, cutoff: 1400,
          pattern: [0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 1, 1, 0, 0] },
        lead: { wave: 'saw', octave: 5, cutoff: 3600, delay: 0.1, on: true,
          pattern: [0, 1, 3, 5, 7, 5, 3, 1, 0, 1, 3, 7, 5, 3, 1, 0] },
        pad: { wave: 'saw', octave: 2, cutoff: 900, on: true, attack: 0.3, release: 0.6 },
        energy: 1.0 },
      { title: 'Low Tide Funeral', artist: 'Hollow Anchor', bpm: 74, bars: 8, swing: 0,
        key: 7, scale: 'minor', progression: [0, 0, 5, 6],
        drums: { kick: K(0, 8), snare: K(4, 12), hat: HAT(0.4, 0.2), ride: K(0, 4, 8, 12) },
        bass: { wave: 'saw', octave: 1, cutoff: 700,
          pattern: [0, null, null, null, null, null, null, null, 5, null, null, null, 6, null, null, null] },
        lead: { wave: 'saw', octave: 4, cutoff: 2000, delay: 0.3, on: true,
          pattern: [0, null, null, 3, null, null, 5, null, null, 3, null, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 2, cutoff: 620, on: true, attack: 1.2, release: 2.4 },
        energy: 0.66 },
    ],
    idents: ['Iron Lung. Turn it up until something rattles.',
      'If you can still hear your engine, you are not listening properly.',
      'Requests go straight in the bin. Enjoy.'],
    ads: [{ brand: 'Gator Hide Boots', line: 'The gator had it coming.' },
      { brand: 'Hammerhead Tools', line: 'Built to outlive your warranty.' }],
  },
  {
    id: 'blue-horizon', name: 'BLUE HORIZON', tagline: 'Ambient drift', genre: 'ambient',
    color: 0x8a5cff, djName: 'Solene',
    tracks: [
      { title: 'Tide Tables', artist: 'Solene', bpm: 70, bars: 8, swing: 0,
        key: 0, scale: 'pentatonic', progression: [0, 3, 0, 4],
        drums: { kick: K(0), snare: new Array(16).fill(0), hat: HAT(0.12, 0.06) },
        bass: { wave: 'sine', octave: 2, cutoff: 420,
          pattern: [0, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null] },
        lead: { wave: 'sine', octave: 5, cutoff: 1400, delay: 0.55, on: true,
          pattern: [0, null, null, null, 4, null, null, null, null, null, 7, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 900, on: true, attack: 3.2, release: 4.0 },
        energy: 0.22 },
      { title: 'Cirrus', artist: 'Wide Field', bpm: 64, bars: 8, swing: 0,
        key: 5, scale: 'major', progression: [0, 4, 3, 4],
        drums: { kick: new Array(16).fill(0), snare: new Array(16).fill(0), hat: HAT(0.08, 0.04) },
        bass: { wave: 'sine', octave: 2, cutoff: 360,
          pattern: [0, null, null, null, null, null, null, null, 4, null, null, null, null, null, null, null] },
        lead: { wave: 'triangle', octave: 5, cutoff: 1200, delay: 0.6, on: true,
          pattern: [2, null, null, null, null, null, 4, null, null, null, null, null, 0, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 760, on: true, attack: 4.0, release: 5.0 },
        energy: 0.18 },
      { title: 'Shore Break', artist: 'Solene', bpm: 76, bars: 8, swing: 0,
        key: 9, scale: 'dorian', progression: [0, 3, 5, 3],
        drums: { kick: K(0, 8), snare: new Array(16).fill(0), hat: HAT(0.16, 0.08), ride: K(4, 12) },
        bass: { wave: 'sine', octave: 2, cutoff: 460,
          pattern: [0, null, null, null, 3, null, null, null, 5, null, null, null, 3, null, null, null] },
        lead: { wave: 'sine', octave: 4, cutoff: 1500, delay: 0.48, on: true,
          pattern: [5, null, null, 3, null, null, null, 0, null, null, null, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1000, on: true, attack: 2.8, release: 3.6 },
        energy: 0.3 },
      { title: 'Long Light', artist: 'Wide Field', bpm: 60, bars: 8, swing: 0,
        key: 2, scale: 'minor', progression: [0, 5, 3, 0],
        drums: { kick: new Array(16).fill(0), snare: new Array(16).fill(0), hat: new Array(16).fill(0) },
        bass: { wave: 'sine', octave: 2, cutoff: 340,
          pattern: [0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null] },
        lead: { wave: 'sine', octave: 5, cutoff: 1100, delay: 0.7, on: true,
          pattern: [0, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 700, on: true, attack: 5.0, release: 6.0 },
        energy: 0.14 },
    ],
    idents: ['Blue Horizon. Breathe out.',
      'No news, no weather, no hurry.',
      'Drive carefully. Or park and just sit for a while.'],
    ads: [{ brand: 'Heron Spa', line: 'Come for the massage. Stay because you fell asleep.' }],
  },
  {
    id: 'the-signal', name: 'THE SIGNAL AM 720', tagline: 'Talk, all day', genre: 'talk',
    color: 0xb0b0b8, djName: 'Roy Vandermeer',
    tracks: [
      { title: 'The Morning Argument', artist: 'Roy Vandermeer', bpm: 70, bars: 8, swing: 0,
        key: 0, scale: 'major', progression: [0, 0, 4, 0],
        drums: { kick: new Array(16).fill(0), snare: new Array(16).fill(0), hat: new Array(16).fill(0) },
        bass: { wave: 'sine', octave: 2, cutoff: 300,
          pattern: [0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null] },
        lead: { wave: 'sine', octave: 4, cutoff: 900, delay: 0.2, on: false,
          pattern: new Array(16).fill(null) },
        pad: { wave: 'saw', octave: 3, cutoff: 600, on: true, attack: 3.0, release: 4.0 },
        energy: 0.1 },
      { title: 'Caller On Line Four', artist: 'Roy Vandermeer', bpm: 70, bars: 8, swing: 0,
        key: 7, scale: 'major', progression: [0, 4, 0, 5],
        drums: { kick: new Array(16).fill(0), snare: new Array(16).fill(0), hat: new Array(16).fill(0) },
        bass: { wave: 'sine', octave: 2, cutoff: 300,
          pattern: [0, null, null, null, null, null, null, null, 4, null, null, null, null, null, null, null] },
        lead: { wave: 'sine', octave: 4, cutoff: 900, delay: 0.2, on: false, pattern: new Array(16).fill(null) },
        pad: { wave: 'saw', octave: 3, cutoff: 620, on: true, attack: 3.0, release: 4.0 },
        energy: 0.12 },
      { title: 'Traffic and Weather', artist: 'Dana Rell', bpm: 70, bars: 8, swing: 0,
        key: 4, scale: 'major', progression: [0, 3, 4, 0],
        drums: { kick: new Array(16).fill(0), snare: new Array(16).fill(0), hat: new Array(16).fill(0) },
        bass: { wave: 'sine', octave: 2, cutoff: 320,
          pattern: [0, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null] },
        lead: { wave: 'sine', octave: 4, cutoff: 900, delay: 0.2, on: false, pattern: new Array(16).fill(null) },
        pad: { wave: 'saw', octave: 3, cutoff: 640, on: true, attack: 3.0, release: 4.0 },
        energy: 0.12 },
      { title: 'Night Line', artist: 'Roy Vandermeer', bpm: 68, bars: 8, swing: 0,
        key: 9, scale: 'minor', progression: [0, 5, 0, 3],
        drums: { kick: new Array(16).fill(0), snare: new Array(16).fill(0), hat: new Array(16).fill(0) },
        bass: { wave: 'sine', octave: 2, cutoff: 300,
          pattern: [0, null, null, null, null, null, null, null, 5, null, null, null, null, null, null, null] },
        lead: { wave: 'sine', octave: 4, cutoff: 880, delay: 0.2, on: false, pattern: new Array(16).fill(null) },
        pad: { wave: 'saw', octave: 3, cutoff: 580, on: true, attack: 3.4, release: 4.4 },
        energy: 0.1 },
    ],
    idents: ['The Signal, seven-twenty AM. Where the city complains to itself.',
      'Our next caller has been holding for forty minutes. I admire that.',
      'Traffic on the causeway is, and I am quoting the helicopter here, "biblical".',
      'A listener writes in to say we are the reason he is late for work. Noted.',
      'Weather: hot. Tomorrow: hot. Long term forecast: hot.'],
    ads: [{ brand: 'Zenith Insurance', line: 'For drivers who have read the news lately.' },
      { brand: 'Candid Legal', line: 'We have seen worse. Probably.' },
      { brand: 'Rapture Realty', line: 'Waterfront property. Ask us about the waterline.' }],
  },
  {
    id: 'coast-rock', name: 'COAST ROCK 104', tagline: 'Guitars and gasoline', genre: 'rock',
    color: 0xff7a29, djName: 'Beau Tanner',
    tracks: [
      { title: 'Two Lane Blacktop', artist: 'The Saltwater Kings', bpm: 134, bars: 8, swing: 0.04,
        key: 4, scale: 'mixolydian', progression: [0, 4, 5, 4],
        drums: { kick: K(0, 6, 8, 14), snare: K(4, 12), hat: HAT(0.7, 0.4), ride: K(0, 2, 4, 6, 8, 10, 12, 14) },
        bass: { wave: 'saw', octave: 2, cutoff: 900,
          pattern: [0, 0, null, 0, 4, null, 4, null, 5, null, 5, null, 4, null, 4, 4] },
        lead: { wave: 'saw', octave: 4, cutoff: 2600, delay: 0.18, on: true,
          pattern: [0, 2, 4, null, 5, 4, 2, null, 0, null, 7, 5, 4, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1100, on: true, attack: 0.6, release: 1.2 },
        energy: 0.9 },
      { title: 'Hurricane Bar', artist: 'Dust & Diesel', bpm: 118, bars: 8, swing: 0.08,
        key: 9, scale: 'blues', progression: [0, 0, 3, 4],
        drums: { kick: K(0, 7, 8, 15), snare: K(4, 12), hat: HAT(0.62, 0.36), open: K(14) },
        bass: { wave: 'triangle', octave: 2, cutoff: 780,
          pattern: [0, null, 0, 3, null, 0, null, 3, 4, null, 4, null, 0, null, 0, null] },
        lead: { wave: 'saw', octave: 4, cutoff: 2300, delay: 0.22, on: true,
          pattern: [0, 3, null, 4, 3, null, 0, null, 4, null, 3, 0, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1000, on: true, attack: 0.8, release: 1.4 },
        energy: 0.76 },
      { title: 'Last Ferry Out', artist: 'The Saltwater Kings', bpm: 96, bars: 8, swing: 0.06,
        key: 2, scale: 'minor', progression: [0, 6, 3, 5],
        drums: { kick: K(0, 8), snare: K(4, 12), hat: HAT(0.48, 0.26), ride: K(2, 6, 10, 14) },
        bass: { wave: 'triangle', octave: 2, cutoff: 680,
          pattern: [0, null, null, 0, 6, null, null, 6, 3, null, null, 3, 5, null, null, null] },
        lead: { wave: 'triangle', octave: 4, cutoff: 2000, delay: 0.3, on: true,
          pattern: [3, null, 5, null, 6, null, 5, 3, 0, null, null, null, null, null, null, null] },
        pad: { wave: 'saw', octave: 3, cutoff: 1050, on: true, attack: 1.4, release: 2.2 },
        energy: 0.54 },
      { title: 'Gasoline Sermon', artist: 'Dust & Diesel', bpm: 146, bars: 8, swing: 0,
        key: 7, scale: 'minor', progression: [0, 5, 6, 5],
        drums: { kick: KV([[0, 1], [2, 0.7], [6, 1], [8, 1], [10, 0.7], [14, 1]]), snare: K(4, 12),
          hat: HAT(0.78, 0.48), open: K(15), clap: K(12) },
        bass: { wave: 'saw', octave: 1, cutoff: 1050,
          pattern: [0, 0, 0, null, 5, 5, null, 5, 6, 6, null, 6, 5, null, 5, 5] },
        lead: { wave: 'saw', octave: 4, cutoff: 3000, delay: 0.14, on: true,
          pattern: [0, 3, 5, 7, 5, 3, 0, null, 5, 7, 8, 7, 5, 3, 0, null] },
        pad: { wave: 'saw', octave: 2, cutoff: 950, on: true, attack: 0.5, release: 1.0 },
        energy: 0.96 },
    ],
    idents: ['Coast Rock one-oh-four. Louder than your exhaust.',
      'That one is about a woman and a carburettor. Mostly the carburettor.',
      'Stay off the shoulder, stay out of the ditch.'],
    ads: [{ brand: 'Bandit Auto Parts', line: 'If we do not have it, you did not need it.' },
      { brand: 'Cactus Tavern', line: 'Cold beer, warm welcome, no questions.' }],
  },
]);

const stationById = new Map(STATIONS.map((s) => [s.id, s]));
export function getStation(id) { return stationById.get(id); }

const SCALES = ['minor', 'major', 'dorian', 'phrygian', 'mixolydian', 'harmonicMinor', 'pentatonic', 'blues'];

/** @param {object[]} [list] the catalogue to check; defaults to the real one. */
export function validateStations(list = STATIONS) {
  const STATIONS = list;
  const problems = [];
  const seen = new Set();
  for (const s of STATIONS) {
    if (seen.has(s.id)) problems.push(`duplicate station ${s.id}`);
    seen.add(s.id);
    if (s.tracks.length < 4) problems.push(`${s.id}: only ${s.tracks.length} tracks`);
    if (!s.idents.length) problems.push(`${s.id}: no idents`);
    for (const t of s.tracks) {
      const w = `${s.id}/${t.title}`;
      if (!SCALES.includes(t.scale)) problems.push(`${w}: unknown scale ${t.scale}`);
      if (t.bpm < 50 || t.bpm > 200) problems.push(`${w}: bpm out of range`);
      if (t.key < 0 || t.key > 11) problems.push(`${w}: key out of range`);
      if (t.swing < 0 || t.swing > 0.3) problems.push(`${w}: swing out of range`);
      if (!Array.isArray(t.progression) || !t.progression.length) problems.push(`${w}: empty progression`);
      for (const name of ['kick', 'snare', 'hat']) {
        const arr = t.drums[name];
        if (!Array.isArray(arr) || arr.length !== 16) { problems.push(`${w}: drums.${name} must be 16 steps`); continue; }
        for (const v of arr) if (!(v >= 0 && v <= 1)) problems.push(`${w}: drums.${name} value out of range`);
      }
      for (const name of ['open', 'clap', 'tom', 'ride']) {
        const arr = t.drums[name];
        if (arr && arr.length !== 16) problems.push(`${w}: drums.${name} must be 16 steps`);
      }
      if (t.bass.pattern.length % 16 !== 0) problems.push(`${w}: bass pattern must be a multiple of 16`);
      if (t.lead.pattern.length % 16 !== 0) problems.push(`${w}: lead pattern must be a multiple of 16`);
      if (!(t.energy >= 0 && t.energy <= 1)) problems.push(`${w}: energy out of range`);
      if (t.bass.octave < 0 || t.bass.octave > 6) problems.push(`${w}: bass octave out of range`);
    }
  }
  if (STATIONS.length < 8) problems.push(`only ${STATIONS.length} stations`);
  return problems;
}
